version: '3.8'

networks:
  app-network:

services:
  gateway:
    image: gateway:1.0.0
    ports:
      - 3000:3000
    command: ["bash", "./deploy.sh", "gateway"]
    networks:
      - app-network
    environment:
      HOST_RMQ: "rabbitmq"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
