version: '3.8'

networks:
  app-network:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: evortex:latest
    container_name: evortex-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./uploads:/usr/src/app/uploads
