version: '3.8'

networks:
  app-network:

services:
  gateway:
    image: gateway:1.0.0
    ports:
      - 3000:3000
    command: ["bash", "./deploy.sh", "gateway"]
    networks:
      - app-network
    environment:
      HOST_RMQ: "rabbitmq"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
  
  auth:
    image: auth:1.0.0
    ports:
      - 3000:3000
    command: ["bash", "./deploy.sh", "auth"]
    networks:
      - app-network
    environment:
      HOST_RMQ: "rabbitmq"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 12345
      RABBITMQ_ERLANG_COOKIE: cluster_cookie
      RABBITMQ_PROMETHEUS_RETENTION_PERIOD: 5m
      CLUSTERED: 'false'
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
